# Generated by Django 6.0.5 on 2026-08-16 10:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='fa-map-pin', help_text='FontAwesome icon class name (e.g., fa-mountain, fa-umbrella-beach, fa-monument, fa-leaf)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('image_url', models.URLField(blank=True, help_text='External image link if no file is uploaded', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, help_text="e.g. God's Own Country, Land of Kings", max_length=200)),
                ('description', models.TextField(help_text='Detailed overview of the state tourism')),
                ('history_culture', models.TextField(blank=True, help_text='Cultural significance and historical background')),
                ('best_time_to_visit', models.CharField(default='October to March', max_length=150)),
                ('climate', models.CharField(default='Tropical / Subtropical', max_length=150)),
                ('languages', models.CharField(default='Hindi, English', max_length=150)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='states/covers/')),
                ('cover_image_url', models.URLField(blank=True, help_text='External cover image URL', max_length=500)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='states/banners/')),
                ('banner_image_url', models.URLField(blank=True, help_text='External wide banner image URL', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('short_summary', models.CharField(help_text='One or two punchy sentences describing the place', max_length=350)),
                ('detailed_description', models.TextField()),
                ('highlights', models.TextField(blank=True, help_text='Comma or line separated key attractions & activities')),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.FloatField(default=20.5937, help_text='GPS Latitude (for interactive maps)')),
                ('longitude', models.FloatField(default=78.9629, help_text='GPS Longitude (for interactive maps)')),
                ('entry_fee', models.CharField(default='Free / ₹50 - ₹200', max_length=120)),
                ('timings', models.CharField(default='06:00 AM - 06:00 PM', max_length=150)),
                ('best_season', models.CharField(default='October - March', max_length=120)),
                ('how_to_reach_air', models.CharField(blank=True, help_text='Nearest airport and distance', max_length=255)),
                ('how_to_reach_train', models.CharField(blank=True, help_text='Nearest railway station', max_length=255)),
                ('how_to_reach_road', models.CharField(blank=True, help_text='Highway and bus connectivity', max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='places/covers/')),
                ('cover_image_url', models.URLField(blank=True, help_text='External cover image URL', max_length=500)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='tourism_app.category')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='tourism_app.state')),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism_app.touristplace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/gallery/')),
                ('image_url', models.URLField(blank=True, help_text='External photo URL', max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tourism_app.touristplace')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TripInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('travelers_count', models.PositiveIntegerField(default=2)),
                ('budget_range', models.CharField(blank=True, default='Moderate (₹10k - ₹25k)', max_length=100)),
                ('message', models.TextField(help_text='Travel preferences, questions, special requests')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Contacted', 'Contacted Traveler'), ('Confirmed', 'Booking Confirmed'), ('Closed', 'Closed / Completed')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tourism_app.touristplace')),
                ('destination_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tourism_app.state')),
            ],
            options={
                'verbose_name_plural': 'Trip Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
