# Generated by Django 6.0.5 on 2026-08-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripinquiry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tripinquiry',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
